<?php

/**
 * @file homepin_url.module
 */

/**
 * Implements hook_menu().
 */
function pin_url_menu() {
  $items['create/pin-from-url'] = array(
    'type' => MENU_CALLBACK,
    'title' => 'Pin from URL',
    'description' => 'Create a Pin from a URL',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('pin_url_create_form'),
    'access arguments' => array('create pin content'),
    'file' => 'pin_url.pages.inc',
  );
  return $items;
}
